#include "mealplanner/planner.hpp"
#include <algorithm>
#include <cmath>
#include <map>
#include <numeric>
#include <random>
#include <stdexcept>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
using json=nlohmann::json;
namespace mealplanner { namespace {
struct Quantity{double value=0.0;std::string unit;};
const json& catalogue(const json& root){if(!root.contains("ingredients")||!root["ingredients"].is_object())throw std::runtime_error("ingredients.json must contain an ingredients object");return root["ingredients"];}
void validate_recipe(const json& r,const json& ingredients){for(auto k:{"id","name","description","macros","buy","pantry","instructions"})if(!r.contains(k))throw std::runtime_error(std::string("Recipe is missing '")+k+"'");if(!r["id"].is_string()||r["id"].get<std::string>().empty())throw std::runtime_error("Recipe id must be a non-empty string");if(!r["name"].is_string()||r["name"].get<std::string>().empty())throw std::runtime_error("Recipe name must be a non-empty string");for(auto k:{"calories_kcal","protein_g","carbs_g","fat_g"})if(!r["macros"].contains(k)||!r["macros"][k].is_number()||r["macros"][k].get<double>()<0)throw std::runtime_error(std::string("Invalid macro field: ")+k);if(!r["buy"].is_array())throw std::runtime_error("Recipe buy field must be an array");for(const auto& item:r["buy"]){if(!item.contains("ingredient_id")||!item.contains("quantity")||!item.contains("unit"))throw std::runtime_error("Every purchased ingredient needs ingredient_id, quantity and unit");std::string id=item["ingredient_id"],unit=item["unit"];double q=item["quantity"];if(q<=0)throw std::runtime_error("Ingredient quantity must be greater than zero: "+id);if(!ingredients.contains(id))throw std::runtime_error("Unknown ingredient id: "+id);if(ingredients.at(id)["pack_unit"].get<std::string>()!=unit)throw std::runtime_error("Unit mismatch for "+id);}}
}
std::string validate_recipe_json(const std::string& recipe_json,const std::string& ingredients_json){json r=json::parse(recipe_json);json i=json::parse(ingredients_json);validate_recipe(r,catalogue(i));return json{{"valid",true},{"id",r["id"]},{"name",r["name"]}}.dump();}
std::string generate_plan_json(const std::string& meals_json,const std::string& ingredients_json,int count,std::uint32_t seed){json meals_root=json::parse(meals_json),ingredients_root=json::parse(ingredients_json);const auto& ingredients=catalogue(ingredients_root);if(!meals_root.contains("meals")||!meals_root["meals"].is_array())throw std::runtime_error("meals.json must contain a meals array");std::vector<json> active;for(const auto& m:meals_root["meals"]){validate_recipe(m,ingredients);if(m.value("active",true))active.push_back(m);}if(count<=0)throw std::runtime_error("Meal count must be greater than zero");if((size_t)count>active.size())throw std::runtime_error("Not enough active recipes for requested meal count");std::vector<size_t> idx(active.size());std::iota(idx.begin(),idx.end(),0);std::mt19937 rng(seed);std::shuffle(idx.begin(),idx.end(),rng);idx.resize((size_t)count);std::map<std::string,Quantity> totals;json selected=json::array();json macros={{"calories_kcal",0.0},{"protein_g",0.0},{"carbs_g",0.0},{"fat_g",0.0}};for(auto n:idx){const auto& m=active[n];selected.push_back({{"id",m["id"]},{"name",m["name"]},{"description",m["description"]},{"macros",m["macros"]}});for(auto k:{"calories_kcal","protein_g","carbs_g","fat_g"})macros[k]=macros[k].get<double>()+m["macros"][k].get<double>();for(const auto& item:m["buy"]){std::string id=item["ingredient_id"],unit=item["unit"];double q=item["quantity"];auto& total=totals[id];if(!total.unit.empty()&&total.unit!=unit)throw std::runtime_error("Unit mismatch while aggregating "+id);total.unit=unit;total.value+=q;}}json shopping=json::array();for(const auto& [id,total]:totals){const auto& meta=ingredients.at(id);double pack_q=meta["pack_quantity"];std::string pack_unit=meta["pack_unit"];if(pack_unit!=total.unit)throw std::runtime_error("Pack unit mismatch for "+id);int packs=std::max(1,(int)std::ceil(total.value/pack_q));shopping.push_back({{"ingredient_id",id},{"name",meta["name"]},{"category",meta["category"]},{"needed",total.value},{"unit",total.unit},{"pack_quantity",pack_q},{"pack_unit",pack_unit},{"packs",packs},{"buy_text",std::to_string(packs)+" x "+meta["name"].get<std::string>()}});}std::sort(shopping.begin(),shopping.end(),[](const json&a,const json&b){if(a["category"]==b["category"])return a["name"].get<std::string>()<b["name"].get<std::string>();return a["category"].get<std::string>()<b["category"].get<std::string>();});return json{{"selected_meals",selected},{"shopping_list",shopping},{"macro_totals",macros}}.dump();}
}
